default:
	g++ source/bch6351.cpp -std=c++2a -o bch6351cpp
	g++ source/bch6345.cpp -std=c++2a -o bch6345cpp
	g++ source/bch4836.cpp -std=c++2a -o bch4836cpp
	g++ source/bch4830.cpp -std=c++2a -o bch4830cpp
